"""empty message

Revision ID: 7c6fc185eeed
Revises: 455cdbf00852
Create Date: 2021-04-05 18:23:58.123588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6fc185eeed'
down_revision = '455cdbf00852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.execute('Update artist SET seeking_venue = True WHERE seeking_venue IS NULL')
    op.alter_column('artist','seeking_venue', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'seeking_venue')
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
